packages:
  - 'packages/*'
  - 'sdk'

allowBuilds:
  esbuild: set this to true or false
  react-intl-universal: set this to true or false

catalog:
  antd: ^5.29.3
  dayjs: ^1.11.21
  es-toolkit: ^1.47.0
  react: ^18.3.1
  react-dom: ^18.3.1
  react-router-dom: ^6.30.2
  zustand: ^5.0.14

  '@types/node': ^24.10.1
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  '@vitejs/plugin-react': ^6.0.2
  globals: ^16.5.0
  typescript: ~5.9.3
  vite: ^8.0.16
  vite-plugin-externals: ^0.6.2

minimumReleaseAgeExclude:
  - '@oxfmt/binding-android-arm-eabi@0.53.0'
  - '@oxfmt/binding-android-arm64@0.53.0'
  - '@oxfmt/binding-darwin-arm64@0.53.0'
  - '@oxfmt/binding-darwin-x64@0.53.0'
  - '@oxfmt/binding-freebsd-x64@0.53.0'
  - '@oxfmt/binding-linux-arm-gnueabihf@0.53.0'
  - '@oxfmt/binding-linux-arm-musleabihf@0.53.0'
  - '@oxfmt/binding-linux-arm64-gnu@0.53.0'
  - '@oxfmt/binding-linux-arm64-musl@0.53.0'
  - '@oxfmt/binding-linux-ppc64-gnu@0.53.0'
  - '@oxfmt/binding-linux-riscv64-gnu@0.53.0'
  - '@oxfmt/binding-linux-riscv64-musl@0.53.0'
  - '@oxfmt/binding-linux-s390x-gnu@0.53.0'
  - '@oxfmt/binding-linux-x64-gnu@0.53.0'
  - '@oxfmt/binding-linux-x64-musl@0.53.0'
  - '@oxfmt/binding-openharmony-arm64@0.53.0'
  - '@oxfmt/binding-win32-arm64-msvc@0.53.0'
  - '@oxfmt/binding-win32-ia32-msvc@0.53.0'
  - '@oxfmt/binding-win32-x64-msvc@0.53.0'
  - '@oxlint/binding-android-arm-eabi@1.68.0'
  - '@oxlint/binding-android-arm64@1.68.0'
  - '@oxlint/binding-darwin-arm64@1.68.0'
  - '@oxlint/binding-darwin-x64@1.68.0'
  - '@oxlint/binding-freebsd-x64@1.68.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.68.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.68.0'
  - '@oxlint/binding-linux-arm64-gnu@1.68.0'
  - '@oxlint/binding-linux-arm64-musl@1.68.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.68.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.68.0'
  - '@oxlint/binding-linux-riscv64-musl@1.68.0'
  - '@oxlint/binding-linux-s390x-gnu@1.68.0'
  - '@oxlint/binding-linux-x64-gnu@1.68.0'
  - '@oxlint/binding-linux-x64-musl@1.68.0'
  - '@oxlint/binding-openharmony-arm64@1.68.0'
  - '@oxlint/binding-win32-arm64-msvc@1.68.0'
  - '@oxlint/binding-win32-ia32-msvc@1.68.0'
  - '@oxlint/binding-win32-x64-msvc@1.68.0'
  - oxfmt@0.53.0
  - oxlint@1.68.0
